[package]
name = "kabletop-godot-sdk"
version = "0.1.0"
authors = ["liyukun <liyukun@cryptape.com>"]
edition = "2018"
# build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.9.3"
kabletop_sdk = { git = "https://github.com/ashuralyk/kabletop-ckb-sdk" }

[build-dependencies]
cc = "1.0.69"

[lib]
crate-type = ["cdylib"]